#! /bin/bash

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# present working directory
DIR=$(dirname $(readlink -e $0))

log_daemon_msg "Creating ~/.tmux.conf symlink"
if ln -s "$DIR/.tmux.conf" $HOME/.tmux.conf; then
    log_end_msg 0
    exit 0
else 
    log_end_msg 1
    exit 1
fi
