#! /bin/bash

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# present working directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# adds path to bashrc script to users /.bashrc
log_daemon_msg "Creating ~/.tmux.conf symlink"
ln -s "$DIR/.tmux.conf" ~/.tmux.conf
log_end_msg 0
